---
title: "Climate analysis"
author: "Manu & Hugo"
date: "4 February 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r config, include=FALSE}
library(magrittr)
library(dplyr)
library(ggplot2)
library(reshape2)
library(mgcv)
library(lubridate)
library(RColorBrewer)
source(file = './utils.R')$value
source(file = './datapaths.R')$value
data_file <- sg_file
```

## Climate analysis

Climate wow nice

## Loading the data

```{r loading, echo=FALSE}
# load data from CSV file
dataraw <- load_epw(data_file)

anadata <- select(dataraw, time.local, 
                  temp = Dry.Bulb.Temperature..C.,
                  rh = Relative.Humidity....)

anadata %>% head %>% print
```

## Temperature heatmap plot

Here is a contour plot for January.

```{r temperature-jan, echo=FALSE}
anadata_e <- create_time_cols(anadata) # add time information

# January contour plot
ggplot(
  head(anadata_e, 24*7*4), 
  aes(x = time.hour, y = time.day, z = temp)) +
  scale_fill_gradient2(low = 'blue', high = 'red', 
                       mid = 'white', midpoint = 27.5) + 
  geom_tile(aes(fill = temp)) + 
  geom_contour(bins = 4, color = 'black')


```

Basic plot with a little bit of smoothing.

```{r temperature-smooth, echo=FALSE}

ggplot(
  anadata_e, 
  aes(x = time.day, y = time.hour, z = temp)) +
  scale_fill_gradient2(low = 'white', high = 'red', 
                       mid = 'yellow', midpoint = 25) + 
  geom_raster(interpolate = TRUE, aes(fill = temp)) +
    theme(legend.position = 'top')
  #geom_contour(bins = 4, color = 'black')

```

Plot with 2d smoothing.

```{r temperature-smooth-butter, echo=FALSE}
anadata_e$temp_s <- smooth_like_butter(anadata_e)

ggplot(
  anadata_e, 
  aes(x = time.day, y = time.hour, z = temp_s)) +
  scale_fill_gradient2(low = 'white', high = 'red', 
                       mid = 'yellow', midpoint = 25) + 
  geom_raster(interpolate = TRUE, aes(fill = temp_s)) +
    theme(legend.position = 'top')

```


We split the smoothed data into levels for the next trick.

```{r temperature-levels, echo=FALSE}

# split the data into levels
anadata_e$tl <- cut(anadata_e$temp, breaks = c(-Inf, 25.9, 27, 29, +Inf))

ggplot(
  head(anadata_e, 31*24), 
  aes(y= time.day, x = time.hour, fill = tl)) +
  scale_fill_manual(name = 'Temperature levels', 
                    values = brewer.pal(name = 'RdBu', 4) %>% rev,
                    labels = c('>21', '>25.9', '>27', '>29')) + 
  geom_tile() +
    theme(legend.position = 'top')

```

Split the data into levels without smoothing.

```{r bar, echo = FALSE}

daily_stats <- dcast(select(anadata_e, time.day, time.hour, temp),
                     time.day ~ time.hour)
daily_stats <- data.frame(
  time.day = daily_stats$time.day,
  av = select(daily_stats, -time.day) %>% apply(1, mean, na.rm = T),
  minmin = select(daily_stats, -time.day) %>% apply(1, min, na.rm = T),
  maxmax = select(daily_stats, -time.day) %>% apply(1, max, na.rm = T)) %>%
  arrange(time.day)
  
ggplot(head(daily_stats, 30), 
       aes(x = time.day, ymin = minmin, ymax = maxmax, color = av)) +
    scale_color_gradient2(low = 'white', high = 'red', 
                       mid = 'yellow', midpoint = 25) + 
  geom_errorbar(linetype = 'solid', position = "dodge", width = 3)

#ggplot(daily_stats,  aes(x = time.day),)
```


Hugo Test
```{r bar, echo = FALSE}

monthly_stats <- dcast(select(anadata_e, time.month, time.mday, time.hour, temp),
                     time.mday + time.hour ~ time.month)

monthly_stats <- data.frame(
  time.month = 1:12,
  av = select(monthly_stats, -time.mday, -time.hour) %>% 
    apply(2, mean, na.rm = T),
  minmin = 
    select(monthly_stats, -time.mday, -time.hour) %>%
    apply(2, min, na.rm = T),
  maxmax = 
    select(monthly_stats, -time.mday, -time.hour) %>%
    apply(2, max, na.rm = T)) %>%
  arrange(time.month)
  
ggplot(monthly_stats, 
       aes(x = time.month, ymin = minmin, ymax = maxmax, color = av)) +
    scale_color_gradient2(low = 'white', high = 'red', 
                       mid = 'yellow', midpoint = 25) + 
  geom_errorbar(linetype = 'solid', position = "dodge", width = 0.25)

#ggplot(daily_stats,  aes(x = time.day),)
```

